version: "3"

tasks:
  tidy:
    cmd: go mod tidy

  proxyproto:
    cmds:
      - protoc -I ./contracts *.proto --go_out=./internal/proxyproto --go-grpc_out=./internal/proxyproto
      - task: tidy

  sqlgen:
    cmds:
      - sqlc generate
      - task: tidy
